<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xuexitest.proto

namespace Xuexitest;

if (false) {
    /**
     * This class is deprecated. Use Xuexitest\TestReply\GetData instead.
     * @deprecated
     */
    class TestReply_GetData {}
}
class_exists(TestReply\GetData::class);
@trigger_error('Xuexitest\TestReply_GetData is deprecated and will be removed in the next major release. Use Xuexitest\TestReply\GetData instead', E_USER_DEPRECATED);

