<?php


namespace App\Observers;


class ArticleObserve extends BaseObserver
{
    protected function clearCache()
    {
        parent::clearCache(); // TODO: Change the autogenerated stub
        file_put_contents('/tmp/test.log','333'.PHP_EOL,FILE_APPEND);
    }

}