<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace Rpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *员工信息
 *
 * Generated from protobuf message <code>rpc.EmployeeInfo</code>
 */
class EmployeeInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *姓名
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     *登录名
     *
     * Generated from protobuf field <code>string login_name = 2;</code>
     */
    private $login_name = '';
    /**
     *工号
     *
     * Generated from protobuf field <code>string employee_id = 3;</code>
     */
    private $employee_id = '';
    /**
     *用户id
     *
     * Generated from protobuf field <code>uint64 user_id = 4;</code>
     */
    private $user_id = 0;
    /**
     *照片
     *
     * Generated from protobuf field <code>repeated .rpc.PictureDataParam photos = 5;</code>
     */
    private $photos;
    /**
     *底片
     *
     * Generated from protobuf field <code>.rpc.PictureDataParam ref_photo = 6;</code>
     */
    private $ref_photo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          姓名
     *     @type string $login_name
     *          登录名
     *     @type string $employee_id
     *          工号
     *     @type int|string $user_id
     *          用户id
     *     @type \Rpc\PictureDataParam[]|\Google\Protobuf\Internal\RepeatedField $photos
     *          照片
     *     @type \Rpc\PictureDataParam $ref_photo
     *          底片
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ai::initOnce();
        parent::__construct($data);
    }

    /**
     *姓名
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *姓名
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *登录名
     *
     * Generated from protobuf field <code>string login_name = 2;</code>
     * @return string
     */
    public function getLoginName()
    {
        return $this->login_name;
    }

    /**
     *登录名
     *
     * Generated from protobuf field <code>string login_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginName($var)
    {
        GPBUtil::checkString($var, True);
        $this->login_name = $var;

        return $this;
    }

    /**
     *工号
     *
     * Generated from protobuf field <code>string employee_id = 3;</code>
     * @return string
     */
    public function getEmployeeId()
    {
        return $this->employee_id;
    }

    /**
     *工号
     *
     * Generated from protobuf field <code>string employee_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmployeeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->employee_id = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>uint64 user_id = 4;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>uint64 user_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *照片
     *
     * Generated from protobuf field <code>repeated .rpc.PictureDataParam photos = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPhotos()
    {
        return $this->photos;
    }

    /**
     *照片
     *
     * Generated from protobuf field <code>repeated .rpc.PictureDataParam photos = 5;</code>
     * @param \Rpc\PictureDataParam[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPhotos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rpc\PictureDataParam::class);
        $this->photos = $arr;

        return $this;
    }

    /**
     *底片
     *
     * Generated from protobuf field <code>.rpc.PictureDataParam ref_photo = 6;</code>
     * @return \Rpc\PictureDataParam
     */
    public function getRefPhoto()
    {
        return $this->ref_photo;
    }

    /**
     *底片
     *
     * Generated from protobuf field <code>.rpc.PictureDataParam ref_photo = 6;</code>
     * @param \Rpc\PictureDataParam $var
     * @return $this
     */
    public function setRefPhoto($var)
    {
        GPBUtil::checkMessage($var, \Rpc\PictureDataParam::class);
        $this->ref_photo = $var;

        return $this;
    }

}

