<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace Rpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *所有员工
 *
 * Generated from protobuf message <code>rpc.EmployeesParam</code>
 */
class EmployeesParam extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .rpc.EmployeeInfo employees = 1;</code>
     */
    private $employees;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rpc\EmployeeInfo[]|\Google\Protobuf\Internal\RepeatedField $employees
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ai::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .rpc.EmployeeInfo employees = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEmployees()
    {
        return $this->employees;
    }

    /**
     * Generated from protobuf field <code>repeated .rpc.EmployeeInfo employees = 1;</code>
     * @param \Rpc\EmployeeInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEmployees($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rpc\EmployeeInfo::class);
        $this->employees = $arr;

        return $this;
    }

}

