<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace Rpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *导入数据情况
 *
 * Generated from protobuf message <code>rpc.ImportReply</code>
 */
class ImportReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_success = 1;</code>
     */
    private $is_success = false;
    /**
     *如果失败, employees记录的是导入失败的员工信息
     *
     * Generated from protobuf field <code>repeated .rpc.EmployeeInfo employees = 2;</code>
     */
    private $employees;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_success
     *     @type \Rpc\EmployeeInfo[]|\Google\Protobuf\Internal\RepeatedField $employees
     *          如果失败, employees记录的是导入失败的员工信息
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ai::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_success = 1;</code>
     * @return bool
     */
    public function getIsSuccess()
    {
        return $this->is_success;
    }

    /**
     * Generated from protobuf field <code>bool is_success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->is_success = $var;

        return $this;
    }

    /**
     *如果失败, employees记录的是导入失败的员工信息
     *
     * Generated from protobuf field <code>repeated .rpc.EmployeeInfo employees = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEmployees()
    {
        return $this->employees;
    }

    /**
     *如果失败, employees记录的是导入失败的员工信息
     *
     * Generated from protobuf field <code>repeated .rpc.EmployeeInfo employees = 2;</code>
     * @param \Rpc\EmployeeInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEmployees($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rpc\EmployeeInfo::class);
        $this->employees = $arr;

        return $this;
    }

}

