<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace Rpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *图片数据参数
 *
 * Generated from protobuf message <code>rpc.PictureDataParam</code>
 */
class PictureDataParam extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 photo_width = 1;</code>
     */
    private $photo_width = 0;
    /**
     * Generated from protobuf field <code>uint32 photo_height = 2;</code>
     */
    private $photo_height = 0;
    /**
     * Generated from protobuf field <code>uint32 format = 3;</code>
     */
    private $format = 0;
    /**
     * Generated from protobuf field <code>bytes photo_datas = 4;</code>
     */
    private $photo_datas = '';
    /**
     * Generated from protobuf field <code>string photo_url = 5;</code>
     */
    private $photo_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $photo_width
     *     @type int $photo_height
     *     @type int $format
     *     @type string $photo_datas
     *     @type string $photo_url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ai::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 photo_width = 1;</code>
     * @return int
     */
    public function getPhotoWidth()
    {
        return $this->photo_width;
    }

    /**
     * Generated from protobuf field <code>uint32 photo_width = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPhotoWidth($var)
    {
        GPBUtil::checkUint32($var);
        $this->photo_width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 photo_height = 2;</code>
     * @return int
     */
    public function getPhotoHeight()
    {
        return $this->photo_height;
    }

    /**
     * Generated from protobuf field <code>uint32 photo_height = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPhotoHeight($var)
    {
        GPBUtil::checkUint32($var);
        $this->photo_height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 format = 3;</code>
     * @return int
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * Generated from protobuf field <code>uint32 format = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFormat($var)
    {
        GPBUtil::checkUint32($var);
        $this->format = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes photo_datas = 4;</code>
     * @return string
     */
    public function getPhotoDatas()
    {
        return $this->photo_datas;
    }

    /**
     * Generated from protobuf field <code>bytes photo_datas = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPhotoDatas($var)
    {
        GPBUtil::checkString($var, False);
        $this->photo_datas = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string photo_url = 5;</code>
     * @return string
     */
    public function getPhotoUrl()
    {
        return $this->photo_url;
    }

    /**
     * Generated from protobuf field <code>string photo_url = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPhotoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->photo_url = $var;

        return $this;
    }

}

