<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto

namespace Rpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *注册人脸参数
 *
 * Generated from protobuf message <code>rpc.RegParam</code>
 */
class RegParam extends \Google\Protobuf\Internal\Message
{
    /**
     *姓名
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     *登录名
     *
     * Generated from protobuf field <code>string login_name = 2;</code>
     */
    private $login_name = '';
    /**
     *工号
     *
     * Generated from protobuf field <code>string employee_id = 3;</code>
     */
    private $employee_id = '';
    /**
     *用户id
     *
     * Generated from protobuf field <code>uint64 user_id = 4;</code>
     */
    private $user_id = 0;
    /**
     *多张图片
     *
     * Generated from protobuf field <code>.rpc.PictureDataParam photo = 5;</code>
     */
    private $photo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          姓名
     *     @type string $login_name
     *          登录名
     *     @type string $employee_id
     *          工号
     *     @type int|string $user_id
     *          用户id
     *     @type \Rpc\PictureDataParam $photo
     *          多张图片
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ai::initOnce();
        parent::__construct($data);
    }

    /**
     *姓名
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *姓名
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *登录名
     *
     * Generated from protobuf field <code>string login_name = 2;</code>
     * @return string
     */
    public function getLoginName()
    {
        return $this->login_name;
    }

    /**
     *登录名
     *
     * Generated from protobuf field <code>string login_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginName($var)
    {
        GPBUtil::checkString($var, True);
        $this->login_name = $var;

        return $this;
    }

    /**
     *工号
     *
     * Generated from protobuf field <code>string employee_id = 3;</code>
     * @return string
     */
    public function getEmployeeId()
    {
        return $this->employee_id;
    }

    /**
     *工号
     *
     * Generated from protobuf field <code>string employee_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmployeeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->employee_id = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>uint64 user_id = 4;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>uint64 user_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     *多张图片
     *
     * Generated from protobuf field <code>.rpc.PictureDataParam photo = 5;</code>
     * @return \Rpc\PictureDataParam
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     *多张图片
     *
     * Generated from protobuf field <code>.rpc.PictureDataParam photo = 5;</code>
     * @param \Rpc\PictureDataParam $var
     * @return $this
     */
    public function setPhoto($var)
    {
        GPBUtil::checkMessage($var, \Rpc\PictureDataParam::class);
        $this->photo = $var;

        return $this;
    }

}

